### ISSUE TITLE
Improve default parameter documentation

### ISSUE THREAD

**Issue by ftavella** [ftavella/schoolStartTime#16]
The current default parameter documentation is not very informative:
https://github.com/ftavella/schoolStartTime/blob/fe1352118e66f538e2e3fcab6523209307ad4891/R/defaultParameters.R#L1
We should add more details to let the users know what each parameter does

**Comment by arjun149** [comment]
(Note for reference) - Remaining Tests to go through 
school.r
sleep.r
twoprocess (check this again)
